CREATE A FUNCTION TO GET THE TOKEN DECIMALS FROM THE BLOCKCHAIN


CREATE A SKELETON FOR LOADING STATE FOR COMPLETEDED VAULTS


----------------- TODAY --------------------

1. CREATE A PROFILE CARD WITH THE USER DATA ABOVE THE PROFILE TABS

2. FETCH THE USER DATA FROM THE DATABASE TO USE INTO EDIT PROFILE TAB

3. 