 // CREATE A FUNCTION TO GET THE TOKEN DECIMALS FROM THE BLOCKCHAIN


CREATE A SKELETON FOR LOADING STATE FOR COMPLETEDED VAULTS


------------------- TODAY ---------------------


2. FETCH THE USER DATA FROM THE DATABASE TO USE INTO EDIT YOUR PROFILE TAB.

